# Generated by Django 3.0.5 on 2020-05-24 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200524_0955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='active_countries',
            new_name='active_countrie',
        ),
        migrations.RenameModel(
            old_name='all_countries',
            new_name='all_countrie',
        ),
        migrations.RenameField(
            model_name='all_countrie',
            old_name='country',
            new_name='coun',
        ),
        migrations.RenameField(
            model_name='all_countrie',
            old_name='country_abr',
            new_name='coun_abr',
        ),
    ]
