# Generated by Django 3.0.5 on 2020-05-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200524_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_countrie',
            name='country',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='all_countrie',
            name='coun',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='info',
            name='country',
            field=models.CharField(max_length=70),
        ),
    ]
