# Generated by Django 3.0.5 on 2020-05-30 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20200530_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active_countrie',
            name='country_abr',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='all_countrie',
            name='coun_abr',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='info',
            name='country_abr',
            field=models.CharField(max_length=10),
        ),
    ]
